#!/bn/sh

cd ${0%/*}

# Source files
. ./dm_exports
. ./dm_alias

[ ! -d ~/Pictures/screenshot ] && mkdir -p ~/Pictures/screenshot
[ ! -d ~/.screenlayout ] && mkdir -p ~/.screenlayout
[ ! -d ~/.bashrc.d ] && mkdir -p ~/.bashrc.d
[ ! -d $DEV_FOLDER ] && mkdir -p $DEV_FOLDER
[ ! -d $TOOLS_FOLDER ] && mkdir -p $TOOLS_FOLDER
[ ! -d $TODOS_OUT_FOLDER ] && mkdir -p $TODOS_OUT_FOLDER
[ ! -d ~/.local/bin ] && mkdir -p ~/.local/bin
[ ! -d ~/.config/gtk-3.0 ] && mkdir -p ~/.config/gtk-3.0
[ ! -d ${WALLPAPER_DIR} ] && mkdir -p ${WALLPAPER_DIR}

for script in ./scripts/*; do
    ln -s ${DOTFILES}/scripts/$(basename ${script}) ~/.local/bin/$(basename ${script})
done

ln -s ${DOTFILES}/bashrc ~/.bashrc
ln -s ${DOTFILES}/vimrc ~/.vimrc
ln -s ${DOTFILES}/pureline.conf ~/.pureline.conf
ln -s ${DOTFILES}/dm_alias ~/.bashrc.d/dm_alias
ln -s ${DOTFILES}/dm_exports ~/.bashrc.d/dm_exports

if [ $OSTYPE == "linux" ]; then
  ln -s ${DOTFILES}/gtkrc-2.0 ~/.gtkrc-2.0
  ln -s ${DOTFILES}/config/settings.ini ~/.config/gtk-3.0/settings.ini
  ln -s ${DOTFILES}/fehbg ~/.fehbg
  ln -s ${DOTFILES}/Xresources ~/.Xresources
fi