#!/bin/bash

set -euo pipefail

# The profiles can be saved running autorandr --save ${profile_name}

activate_monitor() {
    local profile=$1

    autorandr -l ${profile} 
}

use_notebook_monitor() {
    activate_monitor notebook-monitor
}

use_external_home_monitor_if_connected() {
    local extern=HDMI-1

    if xrandr | grep "$extern connected"; then
        activate_monitor external-home-monitor
    fi
}

use_external_office_monitor_if_connected() {
    local extern=DP-2-1

    if xrandr | grep "$extern connected"; then
        activate_monitor external-office-monitor
    fi
}

use_both_home_monitors() {
    echo "Use both home monitor"
    local extern=HDMI-1
   
    if xrandr | grep "$extern connected"; then
         activate_monitor both-home-monitors
    fi
}

use_both_office_monitors() {
    local extern=DP-2-1
   
    if xrandr | grep "$extern connected"; then
         activate_monitor both-office-monitors
    fi
}

required_profile="$1"
echo $required_profile

case $required_profile in
   "external-home-monitor") use_external_home_monitor_if_connected;;
   "notebook-monitor") use_notebook_monitor;;
   "external-office-monitor") use_external_office_monitor_if_connected;;
   "both-office-monitors") use_both_office_monitors;;
   "both-home-monitors") use_both_home_monitors;;
   *) echo "required profile ${required_profile} does not exist";;
esac

notify-send -i display "Display profile" "$(autorandr --current)"
