#!/bin/bash

set -euo pipefail

# The profiles can be saved running arandr
use_script() {
    /bin/sh ~/.screenlayout/$1.sh
}

required_profile="$1"
echo $required_profile

case $required_profile in
   "external-monitor") use_script external-monitor;;
   "notebook-monitor") use_script notebook-monitor;;
   "all-monitors") use_script all-monitors;;
   *) echo "required profile ${required_profile} does not exist";;
esac
