#!/bin/sh

case "$1" in
  lock)
    blurlock "${WALLPAPER}"
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    blurlock "${WALLPAPER}" && systemctl suspend
    ;;
  hibernate)
    blurlock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac
                                                                                                                                                
exit 0



