#!/bin/bash

set -euo pipefail

# The profiles can be saved running autorandr --save ${profile_name}

activate_monitor() {
    local profile=$1

    autorandr -l ${profile} 
}

use_notebook_monitor() {
    activate_monitor notebook-monitor
}

use_external_monitor_if_connected() {
    local extern=HDMI-1

    if xrandr | grep "$extern connected"; then
        activate_monitor external-monitor
    fi
}

current_profile=$(autorandr --current)
echo $current_profile

case $current_profile in
   "external-monitor") use_notebook_monitor;;
   "notebook-monitor") use_external_monitor_if_connected;;
   *) use_notebook_monitor;;
esac

notify-send -i display "Display profile" "$(autorandr --current)"
