#!/bin/bash

set -euo pipefail

# The profiles can be saved running autorandr --save ${profile_name}

activate_monitor() {
    local profile=$1

    autorandr -l ${profile} 
}

use_external_monitor_if_connected() {
    local extern=HDMI-1

    if xrandr | grep "$extern connected"; then
        activate_monitor external-monitor
    fi
}

use_external_monitor_if_connected
notify-send -i display "Display profile" "$(autorandr --current)"
